language: node_js

notifications: # set notification options
  email: false

sudo: false

node_js:
  - "4.1"

services:
  - postgresql

before_script:
  - psql -c 'create database challenges_dev;' -U postgres
  - node models/setup.js
  - npm install -g eslint
script:
  - "eslint ."
  - "npm test"
