version: '3'
services:
  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    volumes:
      - "~/.docker-volumes/challenges/postgresql/data:/var/lib/postgresql/data"
  redis:
    image: "redis:4.0.2"
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
