default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
# As with config/secrets.yml, you never want to store sensitive information,
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: challenges_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: challenges_test
  username: postgres
  password: postgres

production: &production
  <<: *default
  database: challenges_production
  username: challenges
  password: <%= ENV['CHALLENGES_DATABASE_PASSWORD'] %>

staging:
  <<: *production
